import React from 'react';
import { DocPage, DocCallout, DocCodeBlock, DocTable, DocTabs } from '../../components/docs/DocPage';

export const BasketsPage: React.FC = () => {
  const toc = [
    { id: 'overview', title: 'Overview', level: 2 },
    { id: 'elite', title: 'Elite Basket (Super 45)', level: 2 },
    { id: 'quality', title: 'Quality Basket (Good 45)', level: 2 },
    { id: 'growth', title: 'Growth Basket (Dynamic)', level: 2 },
    { id: 'fallen', title: 'Fallen Value Basket', level: 2 },
    { id: 'mapping', title: 'Basket-to-Strategy Mapping', level: 2 },
    { id: 'workflow', title: 'Using Baskets in Workflow', level: 2 },
  ];

  return (
    <DocPage
      title="Understanding Baskets"
      description="Elite, Quality, Growth, and Fallen Value — the four universes. Which basket for which strategy? How they're built and refreshed."
      slug="baskets"
      toc={toc}
      lastUpdated="Jul 2026"
      prevPage={{ title: 'Risk Management', href: '/docs/risk-management' }}
      nextPage={{ title: 'Free Strategies', href: '/docs/free-strategies' }}
      editUrl="https://github.com/marketbeacon/docs/edit/main/pages/baskets.mdx"
    >
      <section id="overview" className="mb-10">
        <h2>Overview</h2>
        <p className="lead">
          Baskets are <strong>curated stock lists</strong> — your first filter. 
          Instead of scanning 5,000+ stocks, you scan 40–80 high-probability names.
        </p>
        <DocTable
          headers={['Basket', 'Universe', 'Count', 'Refresh', 'Best For']}
          rows={[
            ['Elite (Super 45)', 'Fixed list', '~40', 'Quarterly', 'Conservative strategies (Bollinger, Envelope)'],
            ['Quality (Good 45)', 'Fixed list', '~40', 'Quarterly', 'Pro strategies (SMA+BCD, 52W, Cup)'],
            ['Growth', 'Dynamic filter', 'Variable', 'Weekly', 'Alpha strategies (67%, 20% Velocity)'],
            ['Fallen Value', 'Dynamic filter', 'Variable', 'Monthly', 'Deep value / 67% Reset'],
          ]}
        />
      </section>

      <section id="elite" className="mb-10">
        <h2>Elite Basket — Super 45</h2>
        <DocCallout type="tip" title="Conservative Core">
          "Hold forever" quality names. Lowest risk, highest institutional ownership.
        </DocCallout>
        <DocTable
          headers={['Criterion', 'Threshold']}
          rows={[
            ['Business Vintage', '≥ 15 years'],
            ['Net D/E', '< 0.2 (near debt-free)'],
            ['Net Profit', '> ₹200 Cr'],
            ['Market Position', 'Sector leader with pricing power'],
            ['Revenue CAGR', 'Healthy & consistent'],
            ['Profit CAGR', 'Healthy & consistent'],
          ]}
        />
      </section>

      <section id="quality" className="mb-10">
        <h2>Quality Basket — Good 45</h2>
        <DocCallout type="info" title="Growth-Oriented">
          Medium & small-cap focus. Strong fundamentals but higher growth potential than Elite.
        </DocCallout>
        <DocTable
          headers={['Criterion', 'Threshold']}
          rows={[
            ['Focus', 'Mid & Small Cap'],
            ['Fundamentals', 'Strong but growth-oriented'],
            ['Growth', 'Higher than Elite'],
            ['Risk', 'Higher volatility than Elite'],
          ]}
        />
      </section>

      <section id="growth" className="mb-10">
        <h2>Growth Basket — Dynamic Filter</h2>
        <p>Not a fixed list — generated by a scanner filter. Refreshed weekly.</p>
        <DocCodeBlock
          filename="growth-filter.ts"
          language="typescript"
          code={`const GROWTH_FILTER = {
  'D/E': '< 0.5',
  'ROCE': '>= 15%',
  'ROE': '>= 15%',
  'Promoter Pledge': '< 2%',
  'Net Profit': '> ₹50 Cr',
  'Market Cap': '> ₹500 Cr',
  'Revenue YoY': '>= 20%',
  'Profit YoY': '>= 20%',
  'PE': '<= 60',
  'Smart Money': '>= 60%',
};`}
/>
      </section>

      <section id="fallen" className="mb-10">
        <h2>Fallen Value Basket</h2>
        <p>Dynamic filter for deep value / distressed names. Used primarily for 67% Institutional Reset.</p>
        <DocTable
          headers={['Criterion', 'Threshold']}
          rows={[
            ['Drawdown from ATH', '>= 67%'],
            ['Sales TTM', 'Within ±5% of ATH'],
            ['Profit TTM', 'Within ±5% of ATH'],
            ['External Headwind', 'Identified & resolving (policy, macro, sector)'],
            ['Governance', 'Clean — no ongoing litigation/pledge issues'],
          ]}
        />
      </section>

      <section id="mapping" className="mb-10">
        <h2>Basket-to-Strategy Mapping</h2>
        <DocTable
          headers={['Strategy Tier', 'Strategies', 'Eligible Baskets']}
          rows={[
            ['Free', 'Bollinger, Envelope Long/Short', 'Elite + Quality'],
            ['Pro', 'SMA+BCD, 52W, Cup & Handle', 'Elite + Quality'],
            ['Alpha', 'S&R, 67% Reset, 20% Velocity', 'Elite + Quality + Growth + Fallen Value'],
          ]}
        />
      </section>

      <section id="workflow" className="mb-10">
        <h2>Using Baskets in Your Workflow</h2>
        <DocStep number={1} title="Start with Right Universe" description="New investors → Elite. Intermediate → add Quality. Advanced → Growth for alpha strategies." />
        <DocStep number={2} title="Filter in Screener" description="Matrix Screener lets you select basket before choosing strategy." />
        <DocStep number={3} title="Check Basket Tag" description="Every stock page shows its basket (Elite/Quality/Growth/Fallen)." />
        <DocStep number={4} title="Respect Mapping" description="Don't run Alpha strategies on Elite-only baskets — you'll miss opportunities." />
      </section>
    </DocPage>
  );
};

export default BasketsPage;