import React, { useState } from 'react';
import { ShieldCheck } from 'lucide-react';
import LegalModal from '../modals/LegalModal';

const GlobalFooter: React.FC = () => {
  const [legalModal, setLegalModal] = useState<{ open: boolean, type: 'policy' | 'risk' }>({ open: false, type: 'policy' });

  return (
    <>
      <footer className="mt-auto py-16 px-8 border-t border-slate-100 bg-white/50 backdrop-blur-sm">
        <div className="max-w-7xl mx-auto">
          <div className="flex flex-col lg:flex-row justify-between items-start gap-12">
            <div className="space-y-6 max-w-3xl">
              <div className="flex items-center space-x-3 text-slate-950">
                <div className="bg-slate-950 p-1.5 rounded-lg">
                  <ShieldCheck className="h-5 w-5 text-blue-500" />
                </div>
                <span className="text-sm font-black uppercase tracking-[0.2em] italic">Regulatory Matrix Disclosure</span>
              </div>
              <p className="text-[11px] leading-relaxed text-slate-500 font-bold uppercase tracking-tight">
                Institutional Protocol: We are <span className="text-rose-600 underline">NOT SEBI REGISTERED</span> investment advisors.
                All algorithmic data, strategies, and signals generated by MarketBeacon (Batch 9 Engine) are strictly for
                <span className="text-slate-950"> EDUCATIONAL AND QUANTITATIVE RESEARCH PURPOSES ONLY</span>.
              </p>
              <p className="text-[10px] leading-relaxed text-slate-400 font-medium max-w-2xl">
                The financial markets involve significant capital risk. Historical strategy backtests do not guarantee future alpha. 
                Our "No Stop-Loss" methodology is a high-conviction institutional approach and may not be suitable for all risk profiles. 
                Consult a certified financial professional before any monetary commitment.
              </p>
            </div>
            <div className="lg:text-right space-y-4 shrink-0">
              <div className="space-y-1">
                <p className="text-[11px] font-black text-slate-950 uppercase tracking-widest leading-none italic">MarketBeacon<span className="text-blue-600">Pro</span></p>
                <p className="text-[9px] font-bold text-slate-400 uppercase tracking-[0.3em]">Institutional Node v14.0</p>
              </div>
              <div className="pt-4 flex lg:justify-end space-x-6 text-[10px] font-black text-blue-600 uppercase tracking-widest">
                <button onClick={() => setLegalModal({ open: true, type: 'policy' })} className="hover:text-slate-950 transition-colors">Legal Node</button>
                <button onClick={() => setLegalModal({ open: true, type: 'risk' })} className="hover:text-slate-950 transition-colors">Risk Protocol</button>
              </div>
              <p className="text-[9px] font-bold text-slate-300 uppercase tracking-widest pt-4">© 2026 Distributed Ledger Verified</p>
            </div>
          </div>
        </div>
      </footer>

      <LegalModal
        isOpen={legalModal.open}
        onClose={() => setLegalModal({ ...legalModal, open: false })}
        type={legalModal.type}
      />
    </>
  );
};

export default GlobalFooter;
