import React, { useState } from 'react';
import { ShieldCheck } from 'lucide-react';
import LegalModal from '../modals/LegalModal';

const GlobalFooter: React.FC = () => {
  const [legalModal, setLegalModal] = useState<{ open: boolean, type: 'policy' | 'risk' }>({ open: false, type: 'policy' });

  return (
    <>
      <footer className="mt-auto py-10 px-8 border-t border-slate-100 bg-slate-50/50">
        <div className="max-w-7xl mx-auto">
          <div className="flex flex-col md:flex-row justify-between items-start gap-8">
            <div className="space-y-4 max-w-2xl">
              <div className="flex items-center space-x-2 text-slate-900">
                <ShieldCheck className="h-5 w-5 text-blue-600" />
                <span className="text-sm font-black uppercase tracking-widest">MarketBeacon Regulatory Disclosure</span>
              </div>
              <p className="text-[11px] leading-relaxed text-slate-500 font-medium uppercase tracking-tight">
                Important: We are <span className="text-red-600 font-bold underline">NOT SEBI REGISTERED</span> investment advisors.
                All data, strategies, and signals generated by MarketBeacon (Batch 9 Engine) are for
                <span className="text-slate-900 font-bold"> EDUCATIONAL AND RESEARCH PURPOSES ONLY</span>.
                MarketBeacon does not provide personalized investment advice, trading recommendations, or financial consulting.
              </p>
              <p className="text-[10px] leading-relaxed text-slate-400 font-medium">
                Trading in the stock market involves significant risk. Historical performance of our strategies 
                is not a guarantee of future results. No Stop-Loss approach is a high-risk methodology.
                Please consult a SEBI registered financial advisor before making any monetary decisions.
              </p>
            </div>
            <div className="md:text-right space-y-2">
              <p className="text-[10px] font-black text-slate-900 uppercase tracking-widest">© 2026 MarketBeacon Terminal</p>
              <p className="text-[9px] font-bold text-slate-400 uppercase tracking-[0.2em]">Institutional Proprietary Software</p>
              <div className="pt-4 flex md:justify-end space-x-4 text-[9px] font-black text-blue-600 uppercase tracking-widest">
                <button onClick={() => setLegalModal({ open: true, type: 'policy' })} className="hover:underline">Legal Policy</button>
                <button onClick={() => setLegalModal({ open: true, type: 'risk' })} className="hover:underline">Risk Disclosure</button>
              </div>
            </div>
          </div>
        </div>
      </footer>

      <LegalModal
        isOpen={legalModal.open}
        onClose={() => setLegalModal({ ...legalModal, open: false })}
        type={legalModal.type}
      />
    </>
  );
};

export default GlobalFooter;
