import React, { useState } from 'react';
import { ShieldCheck, ArrowUpRight, Lock, BookOpen, Layers, Zap } from 'lucide-react';
import LegalModal from '../modals/LegalModal';
import { Link } from 'react-router-dom';
import BrandLogo from '../brand/BrandLogo';

const GlobalFooter: React.FC = () => {
  const [legalModal, setLegalModal] = useState<{ open: boolean, type: 'policy' | 'risk' }>({ open: false, type: 'policy' });

  return (
    <>
      <footer className="mt-auto py-16 px-6 md:px-12 border-t border-slate-200 bg-white/70 backdrop-blur-md relative z-40">
        <div className="max-w-7xl mx-auto space-y-12">
          
          {/* Main Footer Sitemap Grid */}
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-10">
            {/* Column 1: Info */}
            <div className="space-y-4">
              <BrandLogo variant="light" size={28} />
              <p className="text-[10px] text-slate-500 font-medium leading-relaxed uppercase tracking-wide">
                 India's high-performance quantitative research terminal. Backed by mathematical models and capitulation algorithms.
              </p>
            </div>

            {/* Column 2: Core Terminal */}
            <div className="space-y-3">
              <h4 className="text-[9px] font-black text-slate-400 uppercase tracking-widest">Core Terminal</h4>
              <ul className="space-y-2 text-[10px] font-black text-slate-600 uppercase tracking-wider">
                <li><Link to="/alpha-hub" className="hover:text-blue-600 transition-colors flex items-center gap-1.5"><Layers className="h-3 w-3" /> Alpha Hub</Link></li>
                <li><Link to="/screener" className="hover:text-blue-600 transition-colors flex items-center gap-1.5"><Zap className="h-3 w-3 text-amber-500" /> Screener Matrix</Link></li>
              </ul>
            </div>

            {/* Column 3: Portfolio Desk */}
            <div className="space-y-3">
              <h4 className="text-[9px] font-black text-slate-400 uppercase tracking-widest">Portfolio Desk</h4>
              <ul className="space-y-2 text-[10px] font-black text-slate-600 uppercase tracking-wider">
                <li><Link to="/portfolio" className="hover:text-blue-600 transition-colors flex items-center gap-1.5">Wealth Manager</Link></li>
                <li><Link to="/trades" className="hover:text-blue-600 transition-colors flex items-center gap-1.5"><BookOpen className="h-3 w-3" /> Verified Ledger</Link></li>
                <li><Link to="/license-desk" className="hover:text-blue-600 transition-colors flex items-center gap-1.5">License Desk</Link></li>
              </ul>
            </div>

            {/* Column 4: Links & Channels */}
            <div className="space-y-3">
              <h4 className="text-[9px] font-black text-slate-400 uppercase tracking-widest">External Link</h4>
              <ul className="space-y-2 text-[10px] font-black text-slate-600 uppercase tracking-wider">
                <li><a href="https://t.me/Marketbeconpro" target="_blank" rel="noopener noreferrer" className="hover:text-blue-600 transition-colors inline-flex items-center gap-1">Telegram Alerts <ArrowUpRight className="h-3 w-3 text-slate-400" /></a></li>
                <li><button onClick={() => setLegalModal({ open: true, type: 'policy' })} className="hover:text-blue-600 transition-colors text-left">Legal Protocol</button></li>
                <li><button onClick={() => setLegalModal({ open: true, type: 'risk' })} className="hover:text-blue-600 transition-colors text-left">Risk Disclaimers</button></li>
              </ul>
            </div>
          </div>

          {/* Styled Regulatory Disclaimer box */}
          <div className="bg-slate-50 border border-slate-200 rounded-[2rem] p-6 md:p-8 space-y-4">
            <div className="flex items-center space-x-3 text-slate-900">
              <div className="bg-slate-900 p-2 rounded-xl text-blue-500 border border-slate-800">
                <ShieldCheck className="h-4.5 w-4.5" />
              </div>
              <span className="text-xs font-black uppercase tracking-widest italic">Regulatory Matrix & Advisory Disclaimer</span>
            </div>
            <div className="space-y-3 text-[10px] uppercase font-bold text-slate-500 tracking-wide leading-relaxed">
              <p>
                 Institutional protocol warning: We are <span className="text-rose-600 font-black underline">NOT A SEBI REGISTERED</span> investment advisor or research analyst. All algorithmic models, strategies, holding calculators, and buy/sell signals generated by MarketBeacon (Batch 9 Engine) are purely for <span className="text-slate-950 font-black">EDUCATIONAL AND QUANTITATIVE RESEARCH PURPOSES ONLY</span>.
              </p>
              <p className="text-[9.5px] text-slate-400 leading-normal lowercase first-letter:uppercase">
                 The financial markets involve high capital risk. Past backtest results do not promise future returns or alpha. Our "No Stop-Loss" methodology is a high-conviction institutional approach and may not be suitable for all risk profiles. Consult a certified financial professional before making any real money investments.
              </p>
            </div>
          </div>

          {/* Bottom Row */}
          <div className="flex flex-col sm:flex-row items-center justify-between gap-4 pt-8 border-t border-slate-200 text-[10px] font-black text-slate-400 uppercase tracking-widest">
             <div className="flex items-center gap-2">
                <Lock className="h-3.5 w-3.5 text-slate-300" />
                <span>Distributed Ledger Verified © 2026</span>
             </div>
             <div className="flex items-center gap-1.5">
                <span className="h-1.5 w-1.5 rounded-full bg-emerald-500 animate-pulse" />
                <span>Secure Terminal Environment Connected</span>
             </div>
          </div>

        </div>
      </footer>

      <LegalModal
        isOpen={legalModal.open}
        onClose={() => setLegalModal({ ...legalModal, open: false })}
        type={legalModal.type}
      />
    </>
  );
};

export default GlobalFooter;
export { GlobalFooter };
