import React from 'react';
import { Link } from 'react-router-dom';
import { AlertTriangle, ArrowLeft } from 'lucide-react';
import BrandLogo from '../components/brand/BrandLogo';
import SEO from '../components/SEO';

const DisclaimerPage: React.FC = () => {
  React.useEffect(() => { window.scrollTo(0, 0); }, []);

  const sections = [
    {
      title: '1. Not Investment Advice',
      body: `MarketBeacon Pro is a quantitative research and mathematical modeling tool. It is NOT a SEBI-registered Investment Adviser (IA) or Research Analyst (RA).\n\nAll audit scores, ABCD Tranche zones, strategy signals, and screener results are generated by pre-coded mathematical models using publicly available market data. They are intended for educational, informational, and personal research purposes ONLY.\n\nNothing on this platform constitutes a personalized investment recommendation, buy/sell advisory, or portfolio management service.`
    },
    {
      title: '2. No Guarantee of Accuracy',
      body: `While we strive for accuracy, market data, calculations, and model outputs may contain errors, delays, or omissions.\n\nWe do not guarantee:\n• That any score, signal, or analysis will be accurate or complete\n• That past performance patterns will repeat\n• That any investment strategy will result in profits or prevent losses\n\nMarket conditions change rapidly. Data may be delayed. Always verify independently.`
    },
    {
      title: '3. Risk Warning',
      body: `Investing in securities, derivatives, and equity markets carries significant risk. You could lose some or all of your invested capital.\n\n• Stock prices fluctuate and can go to zero\n• Past performance is NOT indicative of future results\n• Leverage and derivatives amplify both gains and losses\n• Small-cap and mid-cap stocks carry higher volatility risk\n\nYou should only invest money you can afford to lose.`
    },
    {
      title: '4. SEBI Compliance',
      body: `MarketBeacon Pro operates as an educational research platform under the following principles:\n\n• We do NOT provide personalized investment advice\n• We do NOT guarantee returns or predict future performance\n• All users must make their own investment decisions\n• We display clear disclaimers on all analysis pages\n\nWe are not registered with SEBI as an Investment Adviser or Research Analyst. Users requiring personalized advice should consult a SEBI-registered professional.`
    },
    {
      title: '5. Forward-Looking Statements',
      body: `Any projections, simulations, or forward-looking statements on this platform are based on historical data and mathematical assumptions. They do not represent guarantees of future performance.\n\nSimulated performance has inherent limitations:\n• It does not reflect actual trading\n• It may not account for market liquidity, slippage, or transaction costs\n• It may be positively or negatively biased by look-ahead effects\n\nActual trading results may differ materially.`
    },
    {
      title: '6. User Responsibility',
      body: `By using MarketBeacon Pro, you acknowledge:\n\n• You are solely responsible for your investment decisions\n• You understand the risks involved in securities trading\n• You will not hold MarketBeacon Technologies liable for any losses\n• You will consult a SEBI-registered financial advisor before making investment decisions\n\nWe strongly recommend conducting your own due diligence and seeking professional advice.`
    },
    {
      title: '7. Third-Party Data',
      body: `MarketBeacon Pro uses data from third-party sources including NSE, BSE, and other public exchanges. We do not guarantee the accuracy, timeliness, or completeness of third-party data.\n\nAll data is provided "as-is" for informational purposes. We recommend cross-referencing critical data with official exchange sources.`
    },
    {
      title: '8. Contact Us',
      body: `If you have questions about this disclaimer:\n\nEmail: support@marketbeacon.pro\nWhatsApp: +91-70566-33633`
    },
  ];

  return (
    <div className="min-h-screen bg-[var(--bg-primary)] text-[var(--text-primary)] font-sans">
      <SEO title="Disclaimer — SEBI & Risk" description="MarketBeacon Pro disclaimer. Important regulatory and risk disclosures for our stock research platform. Not SEBI registered." />
      <nav className="border-b border-[var(--border-primary)]/60 px-6 md:px-10 py-5 flex items-center justify-between bg-[var(--bg-primary)]/80 sticky top-0 z-50 backdrop-blur-md">
        <Link to="/" className="hover:opacity-80 transition-opacity">
          <BrandLogo variant="dark" size={28} />
        </Link>
        <Link to="/" className="inline-flex items-center gap-2 text-xs font-bold text-[var(--text-muted)] hover:text-[var(--text-primary)] uppercase tracking-wider transition-colors">
          <ArrowLeft className="w-3 h-3" /> Back to Home
        </Link>
      </nav>

      <header className="py-16 px-6 md:px-10 max-w-[800px] mx-auto">
        <div className="inline-flex items-center gap-2 px-4 py-2 bg-amber-500/10 border border-amber-500/20 rounded-full mb-6">
          <AlertTriangle className="h-3.5 w-3.5 text-amber-400" />
          <span className="text-xs font-bold text-amber-400 uppercase tracking-[0.3em]">Regulatory · Risk · Compliance</span>
        </div>
        <h1 className="text-4xl md:text-6xl font-black tracking-tighter text-[var(--text-primary)] mb-4">Disclaimer</h1>
        <p className="text-[var(--text-muted)] text-sm">Effective Date: June 06, 2026 · MarketBeacon Technologies</p>
        <p className="text-[var(--text-muted)] text-sm mt-3 leading-relaxed max-w-xl">
          Important legal, regulatory, and risk disclosures. Please read before using our platform.
        </p>
      </header>

      <main className="px-6 md:px-10 max-w-[800px] mx-auto pb-20">
        <div className="bg-red-500/5 border border-red-500/20 rounded-[1.5rem] p-6 mb-10">
          <p className="text-red-400 text-sm font-bold text-center">
            ⚠️ ALWAYS CONSULT A SEBI-REGISTERED FINANCIAL ADVISOR BEFORE MAKING INVESTMENT DECISIONS. TRADING INVOLVES SUBSTANTIAL RISK OF LOSS.
          </p>
        </div>
        <div className="space-y-10">
          {sections.map((s, i) => (
            <div key={i} className="bg-[var(--bg-secondary)] border border-[var(--border-primary)] rounded-[1.5rem] p-8">
              <h2 className="text-base font-bold text-[var(--text-primary)] mb-4 tracking-tight">{s.title}</h2>
              <div className="space-y-2">
                {s.body.split('\n').map((line, j) => (
                  <p key={j} className={`text-sm leading-relaxed ${line.startsWith('•') ? 'text-[var(--text-secondary)] pl-4' : 'text-[var(--text-muted)]'}`}>
                    {line}
                  </p>
                ))}
              </div>
            </div>
          ))}
        </div>
      </main>

      <div className="border-t border-[var(--border-primary)] py-8 text-center">
<Link to="/" className="text-xs font-bold text-[var(--text-muted)] hover:text-blue-400 uppercase tracking-wider transition-colors">
            ← Back to MarketBeacon Pro
          </Link>
      </div>
    </div>
  );
};

export default DisclaimerPage;
